/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practicasswing;

import java.io.*;
import java.sql.*;  // Paquete necesario para uso de JDBC

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author macpro2
 */
public class Practica6 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Practica6.class.getName());
    private Connection conn;
    private boolean guardado = false;
    /**
     * Creates new form Practica6
     */
    
    public Practica6() {
        initComponents();
        this.lbHrs.setText(Integer.toString(this.sdHrs.getValue()));
        
        try {
            loadDriver();
            System.out.println("Driver de BD cargado exitosamente");
        } catch (ClassNotFoundException ex) {
            System.out.println("Driver de BD no encontrado");
            System.getLogger(Practica6.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (InstantiationException ex) {
            System.out.println("Driver de BD no se pudo cargar en memoria");
            System.getLogger(Practica6.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        } catch (IllegalAccessException ex) {
            System.out.println("Driver de BD sin privilegios de acceso");
            System.getLogger(Practica6.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator2 = new javax.swing.JSeparator();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        rbWin = new javax.swing.JRadioButton();
        rbLnx = new javax.swing.JRadioButton();
        rbMac = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        chPrg = new javax.swing.JCheckBox();
        chGrf = new javax.swing.JCheckBox();
        chAdm = new javax.swing.JCheckBox();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sdHrs = new javax.swing.JSlider();
        btnGuardar = new javax.swing.JButton();
        lbHrs = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Elige un sistema operativo");

        buttonGroup1.add(rbWin);
        rbWin.setSelected(true);
        rbWin.setText("Windows");

        buttonGroup1.add(rbLnx);
        rbLnx.setText("Linux");

        buttonGroup1.add(rbMac);
        rbMac.setText("Mac");

        chPrg.setText("Programación");

        chGrf.setText("Diseño Gráfico");

        chAdm.setText("Administración");

        jLabel2.setText("Horas que dedicas en la PC");

        jLabel3.setText("Uso de la PC");

        sdHrs.setMaximum(24);
        sdHrs.setValue(8);
        sdHrs.addChangeListener(this::sdHrsStateChanged);

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(this::btnGuardarActionPerformed);

        lbHrs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbHrs.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbMac)
                            .addComponent(rbLnx)
                            .addComponent(rbWin)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chGrf)
                            .addComponent(chAdm)
                            .addComponent(chPrg, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sdHrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnGuardar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(lbHrs, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(rbWin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbLnx)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbMac)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chPrg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chGrf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chAdm)
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sdHrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(lbHrs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sdHrsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sdHrsStateChanged
        this.lbHrs.setText(Integer.toString(this.sdHrs.getValue()));
    }//GEN-LAST:event_sdHrsStateChanged

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        this.guardarInfo();
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Practica6().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chAdm;
    private javax.swing.JCheckBox chGrf;
    private javax.swing.JCheckBox chPrg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lbHrs;
    private javax.swing.JRadioButton rbLnx;
    private javax.swing.JRadioButton rbMac;
    private javax.swing.JRadioButton rbWin;
    private javax.swing.JSlider sdHrs;
    // End of variables declaration//GEN-END:variables

    private void guardarInfo() {
        String sSO = "";
        String sPrg = "";
        String sGrf = "";
        String sAdm = "";
        int    iHrs = 0;
        
        if (this.rbWin.isSelected()){
            sSO = "Windows";
        } else if (this.rbLnx.isSelected()){
            sSO = "Linux";
        } else {
            sSO = "Mac";
        }    
    
        sPrg = this.chPrg.isSelected() ? "S" : "N";
        sGrf = this.chGrf.isSelected() ? "S" : "N";
        sAdm = this.chAdm.isSelected() ? "S" : "N";
        
        iHrs = this.sdHrs.getValue();
        
        this.guardado = false;
        
        this.guardarArchivo(sSO,sPrg,sGrf,sAdm,iHrs);
        this.guardarBD(sSO,sPrg,sGrf,sAdm,iHrs);
        
        if (this.guardado)
            JOptionPane.showMessageDialog(this, "Registro guardado.");
    }
    
    private void guardarArchivo(String sSO, String sPrg, String sGrf, String sAdm, int iHrs){
        FileWriter fw = null;
   
        try {
            String strFilename = "encuesta.txt";
            fw = new FileWriter(strFilename,true);
            BufferedWriter out = new BufferedWriter(fw);
            
            out.write(String.format("%s,%s,%s,%s,%d\n",sSO,sPrg,sGrf,sAdm,iHrs));
            
            out.close();
            fw.close();
            guardado = true;
            
            
        } catch (IOException ex) {
            System.getLogger(Practica6.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            guardado = false;
        } finally {
            try {
                fw.close();
            } catch (IOException ex) {
                System.getLogger(Practica6.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        }
    }

    private void guardarBD(String sSO, String sPrg, String sGrf, String sAdm, int iHrs) {
        if (connect()){
            System.out.println("Se pudo conectar");
            
            String stmtSQL = String.format("INSERT INTO respuestas (sSisOper,cProgra,cDiseno,cAdmon,iHoras) VALUES ('%s','%s','%s','%s',%d)",sSO,sPrg,sGrf,sAdm,iHrs);
            
            Statement stmt;
            try {
                stmt = this.conn.createStatement();
                stmt.execute(stmtSQL);
                System.out.println("Inserción realizada correctamente");
                this.guardado = true;
            } catch (SQLException ex) {
                System.getLogger(Practica6.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
                this.guardado = false;
            }
            
            disconnect();
        } else {
            System.out.println("NO se pudo conectar");
        }
            
    }
    
    public void loadDriver() throws ClassNotFoundException, InstantiationException, IllegalAccessException{
        Class.forName("com.mysql.cj.jdbc.Driver");
    }
    
    private boolean connect() {
        boolean conectado = false;
        try {
            this.conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/encuesta?zeroDateTimeBehavior=CONVERT_TO_NULL"
                                                  + "&user=encuesta_user&password=encuesta_pass");
            conectado = true;
            
        } catch (SQLException ex) {
            Logger.getLogger(Practica6.class.getName()).log(Level.SEVERE, null, ex);
        }
        return conectado;
    }
    
    private void disconnect(){
        try {
            this.conn.close();
        } catch (SQLException ex) {
            System.getLogger(Practica6.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }
}
