/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package practicasswing;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author macpro2
 */
public class Practica2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Practica2.class.getName());

    /**
     * Creates new form Practica1
     */
    public Practica2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumInf = new javax.swing.JLabel();
        lblNumSup = new javax.swing.JLabel();
        spNumInf = new javax.swing.JSpinner();
        spNumSup = new javax.swing.JSpinner();
        lblNumGenerado = new javax.swing.JLabel();
        tfNumGenerado = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblNumInf.setText("Num. Inferior");

        lblNumSup.setText("Num. superior");

        spNumInf.addChangeListener(this::spNumInfStateChanged);

        spNumSup.addChangeListener(this::spNumSupStateChanged);

        lblNumGenerado.setText("Num. generado");

        tfNumGenerado.setEditable(false);
        tfNumGenerado.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tfNumGenerado.setText("0");

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(this::btnGenerarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNumGenerado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNumGenerado, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumInf)
                            .addComponent(lblNumSup))
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spNumInf)
                            .addComponent(spNumSup)))
                    .addComponent(btnGenerar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNumInf)
                    .addComponent(spNumInf, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumSup)
                    .addComponent(spNumSup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumGenerado)
                    .addComponent(tfNumGenerado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btnGenerar)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        int min = (Integer)this.spNumInf.getValue();
        int max = (Integer)this.spNumSup.getValue();
        Random rand = new Random();

        // Formula for a random integer between min (inclusive) and max (inclusive)
        int randomNum = rand.nextInt((max - min) + 1) + min;
        
        this.tfNumGenerado.setText(Integer.toString(randomNum));

    }//GEN-LAST:event_btnGenerarActionPerformed

    private void spNumInfStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spNumInfStateChanged
        int min = (Integer)this.spNumInf.getValue();
        int max = (Integer)this.spNumSup.getValue();
        
        if (min>max){
            min = max;
            this.spNumInf.setValue(min);
            JOptionPane.showMessageDialog(this, "El valor minimo no puede ser mayor que el máximo");
        }
    }//GEN-LAST:event_spNumInfStateChanged

    private void spNumSupStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spNumSupStateChanged
                int min = (Integer)this.spNumInf.getValue();
        int max = (Integer)this.spNumSup.getValue();
          
        if (max<min){
            max = min;
            this.spNumSup.setValue(max);
            JOptionPane.showMessageDialog(this, "El valor maximo no puede ser menor que el mínimo");
        }
    }//GEN-LAST:event_spNumSupStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Practica2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JLabel lblNumGenerado;
    private javax.swing.JLabel lblNumInf;
    private javax.swing.JLabel lblNumSup;
    private javax.swing.JSpinner spNumInf;
    private javax.swing.JSpinner spNumSup;
    private javax.swing.JTextField tfNumGenerado;
    // End of variables declaration//GEN-END:variables
}
